title: Ali Babaev # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>    
  Аналитик
  <br><br>    
  Опыт работы 8+ лет в консалтинге/телеком/финтех.
  <br><br>
  Навыки:
  <br><br>  
  <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original-wordmark.svg" width="40" height="40"/>
  <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/pandas/pandas-original-wordmark.svg" width="40" height="40"/>
  <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/numpy/numpy-original-wordmark.svg" width="40" height="40"/>
  <img src="https://seaborn.pydata.org/_images/logo-tall-lightbg.svg width="40" height="40"/>
  <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/oracle/oracle-original.svg" width="40" height="40"/>
  <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/postgresql/postgresql-plain-wordmark.svg" width="40" height="40"/>
  <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/microsoftsqlserver/microsoftsqlserver-plain-wordmark.svg" width="40" height="40"/>
  
  <img src="https://upload.wikimedia.org/wikipedia/ru/0/06/Tableau_logo.svg  width="40" height="40"/>  
  <img src="https://www.stonebranch.com/integration-hub/media/bc/6b/ac/1626255656/PowerBI_Vendor_Product_Logo.svg  width="40" height="40"/>
  



#  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

